//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.269
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAR_P_Studio.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PAR_P_Studio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap CardIcon {
            get {
                object obj = ResourceManager.GetObject("CardIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {\rtf1\ansi\ansicpg1251\deff0\deflang1049{\fonttbl{\f0\fnil\fcharset204 Calibri;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sa200\sl276\slmult1\f0\fs36\&apos;ca\&apos;e0\&apos;f0\&apos;f2\&apos;fb \&apos;eb\&apos;e8\&apos;f7\&apos;ed\&apos;ee\&apos;f1\&apos;f2\&apos;e8, \&apos;e4\&apos;f3\&apos;f8\&apos;e8 \&apos;e8 \&apos;e3\&apos;ee\&apos;e4\&apos;e0\fs22\par
        ///\&apos;d2\&apos;e0\&apos;f0\&apos;ee \&apos;ed\&apos;e5 \&apos;ef\&apos;f0\&apos;e8\&apos;f1\&apos;e2\&apos;e0\&apos;e8\&apos;e2\&apos;e0\&apos;e5\&apos;f2 \&apos;f7\&apos;e5\&apos;eb\&apos;ee\&apos;e2\&apos;e5\&apos;ea\&apos;f3 \&apos;ea\&apos;e0\&apos;ea\&apos;ee\&apos;e3\&apos;ee-\&apos;eb\&apos;e8\&apos;e1\&apos;ee \&apos;f1\&apos;e8\&apos;ec\&apos;e2\&apos;ee\&apos;eb\&apos;e0 \&apos;ed\&apos;e0 \&apos;e2\&apos;f1\&apos;fe \&apos;e6\&apos;e8\&apos;e7\&apos; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string CardsInfo {
            get {
                return ResourceManager.GetString("CardsInfo", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DefaultTaroBack {
            get {
                object obj = ResourceManager.GetObject("DefaultTaroBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Opt {
            get {
                object obj = ResourceManager.GetObject("Opt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon PAR_P_Large {
            get {
                object obj = ResourceManager.GetObject("PAR_P_Large", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vopros {
            get {
                object obj = ResourceManager.GetObject("vopros", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
